name: Run commands on swe hosts file change
on:
 push:
   paths:
     - 'lists/main-hosts.txt'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set timezone
       uses: szenius/set-timezone@v1.2
       with:
         timezoneLinux: "Europe/Stockholm"

     - name: Run shell commands
       run: |
         date=$(date '+%Y-%m-%d %H:%M:%S %Z')
         lines=$(grep -c '' lists/main-hosts.txt)
         sort=$(sort -V lists/main-hosts.txt)

         host_headers=$(cat <<EOF
         # A hosts file that aims to get rid of ads, tracking, scams & badware on (mostly) Swedish websites
         # ----
         # title:          Frellwit's Swedish Hosts File
         # last updated:   ${date}
         # entries:        ${lines}
         # format:         hosts (hosts -- in hosts file format)
         # homepage:       https://github.com/lassekongo83/Frellwits-filter-lists/
         EOF
         )

         echo "$host_headers" > Frellwits-Swedish-Hosts-File.txt
         echo "$sort" >> Frellwits-Swedish-Hosts-File.txt
         echo "Hosts file sorted."

     - name: Commit changes (if any)
       run: |
         timestamp=$(date '+%Y%m%d_%H%M%S')
         git config user.name "GitHub-Actions"
         git config user.email "<>"
         git add Frellwits-Swedish-Hosts-File.txt
         git commit -m "Update swe hosts file ${timestamp}"
         git push
